# Basic Python Workshop - Introduction
In this workshop we will go over importing packages and basic data structures.

For this session we will only import native python packages and do not require interfacing with our custom software. We will work with numpy for numerical analysis, pandas for its convenient data table manipulations, and plotnine for plotting purposes.

# How to import a package
When importing a package there are four main ways to do this.
1. `import package`

    This imports everything in the package and labels all functions and attributes of that package with the package name. For example, if you were to use `import numpy` you would then call the `arange` function from `numpy` by using `numpy.arange`.

2. `import package as shortname`

    This imports the package and labels all functions and attributes of that package with the `shortname` you defined. For example, if you were to use `import numpy as np` you would then call the `arange` function from `numpy` by using `np.arange`.

3. `from package import *`

    This imports all functions and attributes within the package without tagging them as part of the same package. The `*` here means "everything". For example, if you were to use `from numpy import *`, you would then call the `arange` function from `numpy` by using `arange`. This can be dangerous if two packages have the same function and you import the contents of both of them.

4. `from package import function` or `from package import function as shortfun` or `import package.function as shortfun`

   This imports the listed function from the package instead of importing the entire package. The second and third options are identical. If the function or attribute you are importing has attributes of its own, the second and third options are usually useful as you can use a shortened name to call additional attributes (like in bullet point 1)

Don't worry too much about the details of how to use these packages yet. We will get to that later in the workshop.

## First Task
For now, let's import two packages
1. `numpy` as `np`
2. `pandas` as `pd`


In [1]:
import numpy as np
import pandas as pd
from plotnine import *

# Data Types

The most commonly used data types that we will cover are:
* `int` - integer
* `float` - floating point number (decimal places)
* `str` - string
* `list` - an ordered list of objects surrounded by square brackets [ ] and separated by commas
* `dict` - a dictionary of keys and values (may be ordered or unordered)
* `numpy.ndarray` - an array object (think vector or matrix)
* `pandas.DataFrame` - a dataframe object (think table)

If you want to see all the attributes or functions you can use on each of these obect types use the `dir` function. Ex: `dir(list)`

These data types can be sorted into two categories:
1. Mutable: `list`, `dict`, `numpy.array`, `pandas.DataFrame`
2. Immutable: `str`, `float`, `int`

Immutable objects cannot be changed once created, while mutable ones can. This is important because when you are assigning a variable, you are not creating a new object - but instead stating that the variable references an object.

For example, if we say `x = 1`, this means that `x` references the object `1`. If I then say `x = x+1`, it will now say that `x` references the object `2`. You can use the `id` function to show that between these two steps the identity of the variable has changed. This works because 1 and 2 are `int`s and are immutable.

In [2]:
x = 1
print('id of x=1 statement:')
print(id(x))

print('\nid of x=x+1 statement:')
x = x+1
print(id(x))

id of x=1 statement:
187650755318664

id of x=x+1 statement:
187650755318696


What happens now if we try something similar with a mutable object?

Let's try with a `list`. We will first define `x = [1,2,3]`. This is a list with elements 1, 2, and 3. Then we will change the value of the first element in this list to 0 by using `x[0] = 0`. You will see that the id of the variable x stays the same.

In [3]:
x = [1,2,3]
print('id of x=[1,2,3] statement:')
print(id(x))

print('\nvalue of x:')
print(x)

print('\n\nid of x after change:')
x[0] = 0
print(id(x))
print('\nvalue of x after change:')
print(x)

id of x=[1,2,3] statement:
281472201097024

value of x:
[1, 2, 3]


id of x after change:
281472201097024

value of x after change:
[0, 2, 3]


### Mutability
#### Why is mutability a problem?
This can become a problem if you define one want to make a copy of a mutable object and then manipulate it. Say you have a list `x = [1,2,3]` which contains some original set of data. Let's say you then want to make a copy of this list with some additional data added to it. You would like to retain both versions. Because a `list` is mutable, any changes you make to it will propogate.

Let's see how that plays out:
We'll define `y=x`. Then we will `append` a new element to `x` and see what happens to `y`.

In [4]:
x = [1,2,3]
y = x
x.append(4)

print('value of x:')
print(x)

print('\nvalue of y:')
print(y)

value of x:
[1, 2, 3, 4]

value of y:
[1, 2, 3, 4]


#### How to address mutability
If you want to copy and change a mutable object you can get around this issue by using the `.copy()` function. Instead of saying `y=x` it instead says that `y` is a copy of `x`. Then when you change `x`, `y` remains unchanged

In [5]:
x = [1,2,3]
y = x.copy()
x.append(4)

print('value of x:')
print(x)

print('\nvalue of y:')
print(y)

value of x:
[1, 2, 3, 4]

value of y:
[1, 2, 3]


---------
## Floats, stings, and lists
### Second Task - part 1

Define several objects of different types:
* Assign a variable `x` equal to an integer of your choice
* Assign a variable `y` to a float of your choice
* Assign a variable `z` to a string of your choice
* Assign a list `L` to be equal to a list of the above three variables
* Use the `print` function to output the value of the list `L` that you defined

In [6]:
#use this cell to define the variables

x = 54
y = 39.7
z = 'test string'
L = [x, y, z]

In [7]:
#print L in this cell

print(L)

[54, 39.7, 'test string']


There are several ways to interact with lists.

You can use functions (`list.function(*input)`):
* `.append()` - adds object to end of the list
* `.clear()` - removes all items from the list
* `.copy()` - creates a copy of the list
* `.count()` - return number of times the input of the function appears in the list
* `.extend()` - extend a list by adding a new list or other iterable to the end
* `.index()` - returns the index of the input value
* `.insert()` - used as `list.insert(index, object)` - inserts the object at a location before the index
* `.pop()` - remove the entry at the index used in the input to this function and return that object
* `.remove()` - remove the first occurance of the value in the input of this function
* `.reverse()` - reverse the order of the list
* `.sort()` - sort list into ascending order

Besides using these functions you can also interact with lists by using indices. Python begins indexing with 0. So the first element of L is `L[0]`. The last element of L is `L[-1]`. And you can select a subset of values from L by using python index notation `first:last:step` where `first` is the first value to keep, `step` is the step size (1 corresponds to keeping every element, 2 corresponds to every other, etc), and `last` is one index past the last element you wish to keep.

If `first` is missing, the counting starts at index 0. If `last` is missing, the counting goes to the last element of the list. If `step` is missing, you count every element between first and last.

Ex: `L[::2]` counts every other element of `L`. `L[:3]` counts the the first three elements of `L` (`[L[0], L[1], L[2]`).


### Second Task - part 2
Use the functions above to create a new variable L2 which is produced by removing the string in L and sorting the two numbers in numerical order

In [8]:
#define L2 here

#option 1
L2 = (L.copy())[:-1].sort()

#option 2
L2 = L.copy()
L2.remove(z)
L2.sort()

print(L2)

[39.7, 54]


----------

## Numpy Arrays
The most convenient data type for mathematical analysis is the `Numpy` array (an `ndarray` object). This is an n-dimensional array of homogeneous data types (so all `int`, `float`, or `str`). If you have mixed element types within your array, the minimum type will be chosen.

A `Numpy` array is created by using the command `x = np.array(list)`. The list in the array function can be explicitely written out or a previously defined object.

When applying mathematical operations to an array multiplication, addition, and truth statements (>, <, ==) are done elementwise.

Matrix multiplication can be performed by using `@` in place of the `*` symbol, or by using `np.dot()` or `np.outer()` as appropriate

### Third Task
* Define a 1 dimensional array with any 5 elements you desire
* Print the array
* Print the 2nd element in the array
* Multiply this array by 2
* Use `np.dot` and `np.outer` to take the inner and outer product of the array with itself
* Define a second array of the same size
* Add the two arrays together

In [9]:
#define an array
A1 = np.array([1,2,3,4,5])

In [10]:
#print the array
print(A1)

[1 2 3 4 5]


In [11]:
#print the second element of the array
print(A1[1])

2


In [12]:
#multiply the array by 2
print(A1*2)

[ 2  4  6  8 10]


In [13]:
#calculate the inner product
print(np.dot(A1,A1))

55


In [14]:
#calculate the outer product

print(np.outer(A1,A1))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [15]:
#define a second array
A2 = np.array([4,5,6,7,8])

In [16]:
#add the two arrays
A1 + A2

array([ 5,  7,  9, 11, 13])

------------
## Dictionaries
A dictionary is an extremely useful data structure that consists of key-value pairs. The purpose of a dictionary is to allow for indexing by a key, instead of by order. A dictionary is created by using the `{key: value}`. A key may not be a mutable object, such as a list or another dictionary. Each key must also be unique. If another key of the same object is added, it is overwritten. A value can be any object. Some useful methods for a dictionary are:

* `.get(key)` - returns the value of a specified key (can also use `dict[key]`)
* `.pop(key)` - removes key from dictionary and returns value that was removed
* `.keys()` - returns the keys of the dictionary
* `.values()` - returns the value of the dictionary
* `.items()` - returns the dictionary as a list containing the tuple for each key-value pair (useful for iterating)
* `.update(new_dict)` - adds the given dictionary to the dictionary, either updating existing keys or adding new ones
* `.setdefault(key, value)` - returns the value with the specified key, if the key does not exists, inserts it with the value

### Fourth Task

* Create a body weight dictionary named BW_dict for human, cyno, and mouse. The keys should be the species names and the values should be the body weights.

  Note, classic body weights: human = 70, cyno = 3.5, mouse = 0.02
* Call and print the cyno body weight
* Add an entry for rat (bw = 0.25)
* Print the dictionary to see that everything has been added correctly

In [17]:
# create a dictionary:
BW_dict = {'human': 70, 'cyno': 2.5, 'mouse':0.02}

In [18]:
#print the cyno body weight
print(BW_dict['cyno'])

2.5


In [19]:
#add an entry for rat

#option 1:
BW_dict['rat'] = 0.25

#option 2:
BW_dict.update({'rat':0.25})

In [20]:
# print dictionary
print(BW_dict)

{'human': 70, 'cyno': 2.5, 'mouse': 0.02, 'rat': 0.25}


----------------
## Data Frames

Python uses the `pandas` package to create and manipulate data frames. A data frame is a table with labelled columns and rows. Data frames are useful because they can have a mix of different data types as entries. This is particularly helpful when working with string based labels (like species, units, etc) and float or integer data (measurements or parameters).

One of the most commonly used outputs of the QSP notebook is in the form of a data frame. And client data is typically imported as a data frame.

A dataframe can be created in a similar manner as a dictionary by using `df = pd.DataFrame({'column': [list of entries]})`. We will cover importing a dataframe in the introductory plotting notebook.

To call a column from the dataframe you can use either `df['column']` or `df.column`. This second option only works if there are no spaces in the column name.

Rows in a data frame are labeled by `index`. By default these are integers starting at zero - though you many turn a non integer column into indices. To call specific rows you may use similar method as in list and array indexing `df.loc[start:stop:step]`.

Some useful methods for data frames are listed here:
* `.query('condition')` - calls all rows that satisfy a specific condition. Note the condition must be listed as a string and is typically regarding the value of entries in a specific column.
* `.groupby([list of column])` - creates a grouped object collecting all row entries that share the same listed column values
* `.groupby([list of column]).agg(summary statistic)` - creates a new dataframe that summarizes the remaining columns after grouping

### Fifth Task

* Create a dataframe for the following minimal dummy data set:
$$\begin{array}{|c|c|c|c|}
\hline\text{\textbf{species}}& \text{\textbf{output}} & \text{\textbf{unit}} & \text{\textbf{measurement}}\\ \hline \hline
 \text{human}& \text{BW}& \text{kg}& \text{68.5} \\\hline
 \text{human}& \text{BW}& \text{kg}& \text{76.57} \\\hline
 \text{human}& \text{BW}& \text{kg}& \text{68.7} \\\hline
 \text{cyno}& \text{BW}& \text{kg}& \text{3.11} \\\hline
 \text{cyno}& \text{BW}& \text{kg}& \text{2.61} \\\hline
 \text{cyno}& \text{BW}& \text{kg}& \text{3.87} \\\hline
 \text{human}& \text{volume\_central}& \text{L}& \text{2.85} \\\hline
 \text{human}& \text{volume\_central}& \text{L}& \text{3.24} \\\hline
 \text{human}& \text{volume\_central}& \text{L}& \text{3.01} \\\hline
 \text{cyno}& \text{volume\_central}& \text{L}& \text{0.154} \\\hline
 \text{cyno}& \text{volume\_central}& \text{L}& \text{0.153} \\\hline
 \text{cyno}& \text{volume\_central}& \text{L}& \text{0.146}\\\hline
\end{array}$$
* Use `display(...)` to display the data frame you created
* Display just the human measurements
* Display just the body weight measurements
* Group the data frame by species and output and calculate the mean and standard deviation of the measured values
  

In [21]:
# create a data frame
df = pd.DataFrame({'species':['human','human','human','cyno','cyno','cyno','human','human','human','cyno','cyno','cyno'],
                   'output':['BW','BW','BW','BW','BW','BW','volume_central','volume_central','volume_central','volume_central',
                             'volume_central','volume_central'],
                   'unit':['kg','kg','kg','kg','kg','kg','L','L','L','L','L','L'],
                   'measurement':[68.5,76.57,68.7,3.11,2.61,3.87,2.85,3.24,3.01,0.154,0.153,0.146]})

In [22]:
# display the data frame
display(df)

species          output unit  measurement
0    human              BW   kg       68.500
1    human              BW   kg       76.570
2    human              BW   kg       68.700
3     cyno              BW   kg        3.110
4     cyno              BW   kg        2.610
5     cyno              BW   kg        3.870
6    human  volume_central    L        2.850
7    human  volume_central    L        3.240
8    human  volume_central    L        3.010
9     cyno  volume_central    L        0.154
10    cyno  volume_central    L        0.153
11    cyno  volume_central    L        0.146

In [23]:
#display human measurements
display(df.query('species == "human"'))

species          output unit  measurement
0   human              BW   kg        68.50
1   human              BW   kg        76.57
2   human              BW   kg        68.70
6   human  volume_central    L         2.85
7   human  volume_central    L         3.24
8   human  volume_central    L         3.01

In [24]:
#display BW
display(df.query('output == "BW"'))

species output unit  measurement
0   human     BW   kg        68.50
1   human     BW   kg        76.57
2   human     BW   kg        68.70
3    cyno     BW   kg         3.11
4    cyno     BW   kg         2.61
5    cyno     BW   kg         3.87

In [25]:
# group by species and measurement and take statistics
df_stats = df.groupby(['species','output','unit']).agg(['mean','std']).reset_index()
display(df_stats)

species          output unit measurement          
                                      mean       std
0    cyno              BW   kg    3.196667  0.634455
1    cyno  volume_central    L    0.151000  0.004359
2   human              BW   kg   71.256667  4.602568
3   human  volume_central    L    3.033333  0.196044