# Lesson 3: Numpy and Pandas
Numpy and Pandas are common packages used in python. Numpy is a package for doing common mathematical functions. It also has the useful numpy array which allows you to do algebra on arrays of numbers, similar to what you might expect in Matlab. Pandas is standard package for creating tables in python. This tutorial will cover basic use of both numpy and pandas. The first step is importing the packages, which can be done using the import function.

In [2]:
import numpy as np
import pandas as pd

## Numpy
```NumPy``` is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays.
If you're used to using ```MATLAB``` or using large numeric datasets, ```NumPy``` will be particularly useful for you. Numpy is can be more useful than a normal list because it allows you to run the typical operations you might expect on a Matlab vector.

**Built in mathematical methods**

```NumPy``` arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

**Popular in scientific community**

A growing plethora of scientific and mathematical Python-based packages are using ```NumPy``` ```NumPy```; though these typically support Python-sequence input, they convert such input to ```NumPy``` arrays prior to processing, and they often output ```NumPy``` arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use ```NumPy``` arrays.

**Speed and Efficiency:**

```Numpy``` arrays are much more compact than lists. Let's say you have data that's 100 x 100 x 100 = 1 million cells. That isn't terribly big, but it would take about 20 megabytes or so to store it in a list of lists. Whereas with ```NumPy```, it would take about 4MB (depending on the array's datatype). Your computer would be able to handle both of these data structures, but scalability is clearly an issue.

For more reading please see this [quickstart guide](https://docs.scipy.org/doc/numpy/user/quickstart.html).

At the core of the ```NumPy``` package, is the ```ndarray``` object. This encapsulates n-dimensional arrays of homogeneous data types.

In [2]:
# Creating a numpy array
a = [0,1,2,3]
x = np.array(a)
type(x)

numpy.ndarray

* ```NumPy``` arrays have a **fixed size** at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a ```NumPy``` array are all required to be of the **same data type**, and thus will be the same size in memory. The exception: one can have arrays of (Python, including ```NumPy```) objects, thereby allowing for arrays of different sized elements.

* When creating the array it is important to keep in mind what you are entering, if the dtype is not specified, it will automatically choose the minimum type needed to define all the items, which may lead to using a type not suited for what you are planning to do.

In [3]:
# Comparing types inside array
# Type for 1st is integers
x = np.array([0,1,2,3])
print(type(x[0]))
# Type for 2nd is strings even though the first item is an integer
x = np.array([0,1,'NaN'])
print(type(x[0]))

<class 'numpy.int64'>
<class 'numpy.str_'>


### Example mathematical operations

In [4]:
x = np.array([0, 1, 2, 3])
print(f"x = {x}")
# Multiplication is done elementwise
print(f"x * 4 = {x * 4}")
print(f"x / 4 = {x / 4}")
print(f"x > 1 = {x > 1}")
# Matrix product
print(f"x @ [4,3,2,1] (Matrix Product) = {x @ [4,3,2,1]}")

x = [0 1 2 3]
x * 4 = [ 0  4  8 12]
x / 4 = [0.   0.25 0.5  0.75]
x > 1 = [False False  True  True]
x @ [4,3,2,1] (Matrix Product) = 10


### Indexing
Indexing for numpy works similarly to Matlab, except with some python twists. 
* Indexing is done starting at 0. 
* Similar to lists, it is inclusive for the starting value and exclusive for the ending value

Indexing works with the form `[start:end:step]` with commas separating different dimensions.

In [5]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
print("Single slice, does not return as an array but as the item type:")
print(x[2])
print("1-D slice, from the 3rd item to the 11th not including the 11th:")
print(x[2:10])
print("""Can leave spot blank to use defaults
start defaults to first item
end defaults to last item
step defaults to 1:""")
print(x[2:])
print("Can use negatives in step to reverse direction of array:")
print(x[5::-1])

Single slice, does not return as an array but as the item type:
2
1-D slice, from the 3rd item to the 11th not including the 11th:
[2 3 4 5 6 7 8 9]
Can leave spot blank to use defaults
start defaults to first item
end defaults to last item
step defaults to 1:
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
Can use negatives in step to reverse direction of array:
[5 4 3 2 1 0]


### Multidimensional indexing
Multidimensional indexing follows the same conventions as 1-D indexing, with commas between them.

In [7]:
y = np.random.randint(30, size=30).reshape(2, 5, 3)
y

array([[[ 3,  7,  6],
        [15, 11, 26],
        [25, 18,  6],
        [15, 21, 13],
        [ 8, 20, 15]],

       [[22, 23, 10],
        [ 1, 26,  1],
        [16,  9, 21],
        [19,  7, 10],
        [22, 17, 16]]])

In [8]:
print("Indexing an individual item")
print(y[1,3,2])
print("Use semicolons all items of that dimension, ie all rows or columns")
print(y[1,:,2])
print("Ellipses can be used to assume semicolons for everything else")
print(y[...,2])
print(y[:,:,2])

Indexing an individual item
10
Use semicolons all items of that dimension, ie all rows or columns
[10  1 21 10 16]
Ellipses can be used to assume semicolons for everything else
[[ 6 26  6 13 15]
 [10  1 21 10 16]]
[[ 6 26  6 13 15]
 [10  1 21 10 16]]


You can also put conditions for slicing and it will return an array consisting of the items that pass. However it will be flattened to a 1 dimensional array. For more specific conditional indexing, see the [`where` function](https://numpy.org/doc/stable/reference/generated/numpy.where.html) in numpy.

In [9]:
y[y>20]

array([26, 25, 21, 22, 23, 26, 21, 22])

### Transforming Arrays
transforming arrays generally use functions instead of mathematical functions like lists.

In [10]:
# We use double brackets for x because we need a 2 dimensional array to concatenate them together
x = np.array([[1, 2, 3]])
y = np.arange(15).reshape(3, 5)
print(x)
print(y)

[[1 2 3]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
print(f"Numpy array, array[1,2,3] * 4: {x * 4}")
print(f"Normal list, [1,2,3] * 4:      {[1,2,3] * 4}")

Numpy array, array[1,2,3] * 4: [[ 4  8 12]]
Normal list, [1,2,3] * 4:      [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


To get the dimensions of an array, you can use the shape function.

In [12]:
#get dimensions of an array
print(y.shape)
print(x.shape)

(3, 5)
(1, 3)


### Concatenate arrays
To concatenate arrays together, you can use the `concatenate` method. The first argument is a list of the arrays you want to concatenate. The second is axis, which states what dimension to concatenate together. When concatenating, the arrays must have the same shape, except for the axis that is being concatenated. To get the same shape, we need to transpose one of the arrays. We can use the `T` method for this.

In [13]:
# Transposing array
x = x.T
# Checking shape
print(x.shape)
# Concatenating together
print(np.concatenate([y,x], axis = 1))

(3, 1)
[[ 0  1  2  3  4  1]
 [ 5  6  7  8  9  2]
 [10 11 12 13 14  3]]


### Aggregation functions
There are also several aggregation function such as sum, mean, or prod. For a list of aggregation/statistical functions [see here](https://www.pythonprogramming.in/numpy-aggregate-and-statistical-functions.html). Most follow the standard syntax of `function(array, axis=dimension)`, where the axis is the dimension you want to do the aggregation function on.

In [14]:
# Example aggregation functions
print(np.sum(y,axis=1))
print(np.mean(y,axis=0))

[10 35 60]
[5. 6. 7. 8. 9.]


## Pandas

This class introduces the pandas package which is centered around the pandas' DataFrame and Series datatypes. Unlike NumPy, DataFrames can store multiple data types, like ints and strings. Typically, pandas is useful for analyzing data that have multiple entries in separate rows and different information in each column. You can think of a Series (1-dimensional) as one column of data while a DataFrame is made up of multiple columns (2-dimensional). We're primarily focusing on the DataFrame class in this lecture, but it's important for you to know that there are differences between the two datatypes. Additional resources can be found here:

* 10 minute quick introduction: https://pandas.pydata.org/pandas-docs/stable/10min.html
* Merge, Joining and Concatenating dataframes: https://pandas.pydata.org/pandas-docs/stable/merging.html
* More on indexing: https://pandas.pydata.org/pandas-docs/stable/indexing.html

For an example dataset, we will use the cars dataset, which is an example dataset giving information on car brands. We can load the csv file using the read_csv function. We can use the head function to take a quick look at the table we loaded. We can take a look at the index and columns of the dataframe using the `index` and `columns`. You can also use this to rename them if desired.

In [23]:
cars = pd.read_csv("cars.csv")
cars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [24]:
print(cars.index)
print(cars.columns)

RangeIndex(start=0, stop=32, step=1)
Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')


In [25]:
cars.columns = [
    "brand",
    "mpg",
    "cylinders",
    "displacement",
    "horsepower",
    "rear_axle_ratio",
    "weight",
    "quarter_mile_time",
    "engine_type",
    "transmission",
    "gears",
    "carburetors"
]
cars.head()

brand   mpg  cylinders  displacement  horsepower  \
0          Mazda RX4  21.0          6         160.0         110   
1      Mazda RX4 Wag  21.0          6         160.0         110   
2         Datsun 710  22.8          4         108.0          93   
3     Hornet 4 Drive  21.4          6         258.0         110   
4  Hornet Sportabout  18.7          8         360.0         175   

   rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
0             3.90   2.620              16.46            0             1   
1             3.90   2.875              17.02            0             1   
2             3.85   2.320              18.61            1             1   
3             3.08   3.215              19.44            1             0   
4             3.15   3.440              17.02            0             0   

   gears  carburetors  
0      4            4  
1      4            4  
2      4            1  
3      3            1  
4      3            2

We can gather information about the data various functions such as `describe` and `info`. Describe gives statistical information such as mean, standard deviation, minimum and maximum. Info gives the columns, the number of non-null values, and the type of each column.

In [26]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   brand              32 non-null     object 
 1   mpg                32 non-null     float64
 2   cylinders          32 non-null     int64  
 3   displacement       32 non-null     float64
 4   horsepower         32 non-null     int64  
 5   rear_axle_ratio    32 non-null     float64
 6   weight             32 non-null     float64
 7   quarter_mile_time  32 non-null     float64
 8   engine_type        32 non-null     int64  
 9   transmission       32 non-null     int64  
 10  gears              32 non-null     int64  
 11  carburetors        32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [27]:
cars.describe()

mpg  cylinders  displacement  horsepower  rear_axle_ratio  \
count  32.000000  32.000000     32.000000   32.000000        32.000000   
mean   20.090625   6.187500    230.721875  146.687500         3.596563   
std     6.026948   1.785922    123.938694   68.562868         0.534679   
min    10.400000   4.000000     71.100000   52.000000         2.760000   
25%    15.425000   4.000000    120.825000   96.500000         3.080000   
50%    19.200000   6.000000    196.300000  123.000000         3.695000   
75%    22.800000   8.000000    326.000000  180.000000         3.920000   
max    33.900000   8.000000    472.000000  335.000000         4.930000   

          weight  quarter_mile_time  engine_type  transmission      gears  \
count  32.000000          32.000000    32.000000     32.000000  32.000000   
mean    3.217250          17.848750     0.437500      0.406250   3.687500   
std     0.978457           1.786943     0.504016      0.498991   0.737804   
min     1.513000          14.500000     0.000000      0.000000   3.000000   
25%     2.581250          16.892500     0.000000      0.000000   3.000000   
50%     3.325000          17.710000     0.000000      0.000000   4.000000   
75%     3.610000          18.900000     1.000000      1.000000   4.000000   
max     5.424000          22.900000     1.000000      1.000000   5.000000   

       carburetors  
count      32.0000  
mean        2.8125  
std         1.6152  
min         1.0000  
25%         2.0000  
50%         2.0000  
75%         4.0000  
max         8.0000

### Indexing
Indexing can be done by columns and rows. If you want to take a subset of both columns and rows, you can use either the `loc` or `iloc` function. `loc` is used for slicing by labels, while `iloc` is by integer position of the rows and columns. Note that `loc` is inclusive for both the beginning and the end, but `iloc` follows the typical python indexing of inclusive start but exclusive end.

In [28]:
# Columns can be indexed either way
cars.mpg
cars["mpg"]

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [29]:
# rows can be indexed similarly to lists
cars[0:4]

brand   mpg  cylinders  displacement  horsepower  rear_axle_ratio  \
0       Mazda RX4  21.0          6         160.0         110             3.90   
1   Mazda RX4 Wag  21.0          6         160.0         110             3.90   
2      Datsun 710  22.8          4         108.0          93             3.85   
3  Hornet 4 Drive  21.4          6         258.0         110             3.08   

   weight  quarter_mile_time  engine_type  transmission  gears  carburetors  
0   2.620              16.46            0             1      4            4  
1   2.875              17.02            0             1      4            4  
2   2.320              18.61            1             1      4            1  
3   3.215              19.44            1             0      3            1

In [30]:
cars.loc[4:8,["cylinders","horsepower"]]

cylinders  horsepower
4          8         175
5          6         105
6          8         245
7          4          62
8          4          95

In [31]:
# Same slice but using iloc
cars.iloc[4:8,2:4]

cylinders  displacement
4          8         360.0
5          6         225.0
6          8         360.0
7          4         146.7

### Sorting 
Sorting can be done using the sort_values function. You can sort by multiple columns at once. If you sort multiple columns the extra columns will be used to break ties in the order given. Sorting maintains the order of ties so you can also do two different sorts if you would like to have one be ascending and the other be descending.

In [36]:
# Sort values, by indicates which columns, it can be a list, and it will be sorted in that order
# can set ascending to True or False
cars.sort_values(by=["cylinders", "mpg"], ascending=False)

brand   mpg  cylinders  displacement  horsepower  \
24     Pontiac Firebird  19.2          8         400.0         175   
4     Hornet Sportabout  18.7          8         360.0         175   
12           Merc 450SL  17.3          8         275.8         180   
11           Merc 450SE  16.4          8         275.8         180   
28       Ford Pantera L  15.8          8         351.0         264   
21     Dodge Challenger  15.5          8         318.0         150   
13          Merc 450SLC  15.2          8         275.8         180   
22          AMC Javelin  15.2          8         304.0         150   
30        Maserati Bora  15.0          8         301.0         335   
16    Chrysler Imperial  14.7          8         440.0         230   
6            Duster 360  14.3          8         360.0         245   
23           Camaro Z28  13.3          8         350.0         245   
14   Cadillac Fleetwood  10.4          8         472.0         205   
15  Lincoln Continental  10.4          8         460.0         215   
3        Hornet 4 Drive  21.4          6         258.0         110   
0             Mazda RX4  21.0          6         160.0         110   
1         Mazda RX4 Wag  21.0          6         160.0         110   
29         Ferrari Dino  19.7          6         145.0         175   
9              Merc 280  19.2          6         167.6         123   
5               Valiant  18.1          6         225.0         105   
10            Merc 280C  17.8          6         167.6         123   
19       Toyota Corolla  33.9          4          71.1          65   
17             Fiat 128  32.4          4          78.7          66   
18          Honda Civic  30.4          4          75.7          52   
27         Lotus Europa  30.4          4          95.1         113   
25            Fiat X1-9  27.3          4          79.0          66   
26        Porsche 914-2  26.0          4         120.3          91   
7             Merc 240D  24.4          4         146.7          62   
2            Datsun 710  22.8          4         108.0          93   
8              Merc 230  22.8          4         140.8          95   
20        Toyota Corona  21.5          4         120.1          97   
31           Volvo 142E  21.4          4         121.0         109   

    rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
24             3.08   3.845              17.05            0             0   
4              3.15   3.440              17.02            0             0   
12             3.07   3.730              17.60            0             0   
11             3.07   4.070              17.40            0             0   
28             4.22   3.170              14.50            0             1   
21             2.76   3.520              16.87            0             0   
13             3.07   3.780              18.00            0             0   
22             3.15   3.435              17.30            0             0   
30             3.54   3.570              14.60            0             1   
16             3.23   5.345              17.42            0             0   
6              3.21   3.570              15.84            0             0   
23             3.73   3.840              15.41            0             0   
14             2.93   5.250              17.98            0             0   
15             3.00   5.424              17.82            0             0   
3              3.08   3.215              19.44            1             0   
0              3.90   2.620              16.46            0             1   
1              3.90   2.875              17.02            0             1   
29             3.62   2.770              15.50            0             1   
9              3.92   3.440              18.30            1             0   
5              2.76   3.460              20.22            1             0   
10             3.92   3.440              18.90            1             0   
19           

In [37]:
# Chaining sorts maintains previous sorts, so you can use this to assort by ascending and decending
sort_1 = cars.sort_values(by=["cylinders"], ascending=True)
sort_2 = sort_1.sort_values(by=['mpg'], ascending=False)
sort_2

brand   mpg  cylinders  displacement  horsepower  \
19       Toyota Corolla  33.9          4          71.1          65   
17             Fiat 128  32.4          4          78.7          66   
27         Lotus Europa  30.4          4          95.1         113   
18          Honda Civic  30.4          4          75.7          52   
25            Fiat X1-9  27.3          4          79.0          66   
26        Porsche 914-2  26.0          4         120.3          91   
7             Merc 240D  24.4          4         146.7          62   
2            Datsun 710  22.8          4         108.0          93   
8              Merc 230  22.8          4         140.8          95   
20        Toyota Corona  21.5          4         120.1          97   
31           Volvo 142E  21.4          4         121.0         109   
3        Hornet 4 Drive  21.4          6         258.0         110   
0             Mazda RX4  21.0          6         160.0         110   
1         Mazda RX4 Wag  21.0          6         160.0         110   
29         Ferrari Dino  19.7          6         145.0         175   
24     Pontiac Firebird  19.2          8         400.0         175   
9              Merc 280  19.2          6         167.6         123   
4     Hornet Sportabout  18.7          8         360.0         175   
5               Valiant  18.1          6         225.0         105   
10            Merc 280C  17.8          6         167.6         123   
12           Merc 450SL  17.3          8         275.8         180   
11           Merc 450SE  16.4          8         275.8         180   
28       Ford Pantera L  15.8          8         351.0         264   
21     Dodge Challenger  15.5          8         318.0         150   
13          Merc 450SLC  15.2          8         275.8         180   
22          AMC Javelin  15.2          8         304.0         150   
30        Maserati Bora  15.0          8         301.0         335   
16    Chrysler Imperial  14.7          8         440.0         230   
6            Duster 360  14.3          8         360.0         245   
23           Camaro Z28  13.3          8         350.0         245   
14   Cadillac Fleetwood  10.4          8         472.0         205   
15  Lincoln Continental  10.4          8         460.0         215   

    rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
19             4.22   1.835              19.90            1             1   
17             4.08   2.200              19.47            1             1   
27             3.77   1.513              16.90            1             1   
18             4.93   1.615              18.52            1             1   
25             4.08   1.935              18.90            1             1   
26             4.43   2.140              16.70            0             1   
7              3.69   3.190              20.00            1             0   
2              3.85   2.320              18.61            1             1   
8              3.92   3.150              22.90            1             0   
20             3.70   2.465              20.01            1             0   
31             4.11   2.780              18.60            1             1   
3              3.08   3.215              19.44            1             0   
0              3.90   2.620              16.46            0             1   
1              3.90   2.875              17.02            0             1   
29             3.62   2.770              15.50            0             1   
24             3.08   3.845              17.05            0             0   
9              3.92   3.440              18.30            1             0   
4              3.15   3.440              17.02            0             0   
5              2.76   3.460              20.22            1             0   
10             3.92   3.440              18.90            1             0   
12             3.07   3.730              17.60            0             0   
11           

### Filtering
There are many methods to filter dataframes, but we will cover some common filters. Filtering NaN values requires special filters,
there are several listed here:

* isnull() - returns the dataframe with True or False if the entry at that spot is a NaN value
* dropna() - drops any rows that have NaN values
* fillna(value) - replaces any NaN values with the specified value

In [25]:
# Replaces any entry containing the first term with the second term
cars.replace("Honda Civic", "Civic")

brand   mpg  cylinders  displacement  horsepower  \
0             Mazda RX4  21.0          6         160.0         110   
1         Mazda RX4 Wag  21.0          6         160.0         110   
2            Datsun 710  22.8          4         108.0          93   
3        Hornet 4 Drive  21.4          6         258.0         110   
4     Hornet Sportabout  18.7          8         360.0         175   
5               Valiant  18.1          6         225.0         105   
6            Duster 360  14.3          8         360.0         245   
7             Merc 240D  24.4          4         146.7          62   
8              Merc 230  22.8          4         140.8          95   
9              Merc 280  19.2          6         167.6         123   
10            Merc 280C  17.8          6         167.6         123   
11           Merc 450SE  16.4          8         275.8         180   
12           Merc 450SL  17.3          8         275.8         180   
13          Merc 450SLC  15.2          8         275.8         180   
14   Cadillac Fleetwood  10.4          8         472.0         205   
15  Lincoln Continental  10.4          8         460.0         215   
16    Chrysler Imperial  14.7          8         440.0         230   
17             Fiat 128  32.4          4          78.7          66   
18                Civic  30.4          4          75.7          52   
19       Toyota Corolla  33.9          4          71.1          65   
20        Toyota Corona  21.5          4         120.1          97   
21     Dodge Challenger  15.5          8         318.0         150   
22          AMC Javelin  15.2          8         304.0         150   
23           Camaro Z28  13.3          8         350.0         245   
24     Pontiac Firebird  19.2          8         400.0         175   
25            Fiat X1-9  27.3          4          79.0          66   
26        Porsche 914-2  26.0          4         120.3          91   
27         Lotus Europa  30.4          4          95.1         113   
28       Ford Pantera L  15.8          8         351.0         264   
29         Ferrari Dino  19.7          6         145.0         175   
30        Maserati Bora  15.0          8         301.0         335   
31           Volvo 142E  21.4          4         121.0         109   

    rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
0              3.90   2.620              16.46            0             1   
1              3.90   2.875              17.02            0             1   
2              3.85   2.320              18.61            1             1   
3              3.08   3.215              19.44            1             0   
4              3.15   3.440              17.02            0             0   
5              2.76   3.460              20.22            1             0   
6              3.21   3.570              15.84            0             0   
7              3.69   3.190              20.00            1             0   
8              3.92   3.150              22.90            1             0   
9              3.92   3.440              18.30            1             0   
10             3.92   3.440              18.90            1             0   
11             3.07   4.070              17.40            0             0   
12             3.07   3.730              17.60            0             0   
13             3.07   3.780              18.00            0             0   
14             2.93   5.250              17.98            0             0   
15             3.00   5.424              17.82            0             0   
16             3.23   5.345              17.42            0             0   
17             4.08   2.200              19.47            1             1   
18             4.93   1.615              18.52            1             1   
19             4.22   1.835              19.90            1             1   
20             3.70   2.465              20.01            1             0   
21           

In [26]:
# Extract all rows whose values match a certain criteria for a specific row
cars[cars["cylinders"] >= 6]

brand   mpg  cylinders  displacement  horsepower  \
0             Mazda RX4  21.0          6         160.0         110   
1         Mazda RX4 Wag  21.0          6         160.0         110   
3        Hornet 4 Drive  21.4          6         258.0         110   
4     Hornet Sportabout  18.7          8         360.0         175   
5               Valiant  18.1          6         225.0         105   
6            Duster 360  14.3          8         360.0         245   
9              Merc 280  19.2          6         167.6         123   
10            Merc 280C  17.8          6         167.6         123   
11           Merc 450SE  16.4          8         275.8         180   
12           Merc 450SL  17.3          8         275.8         180   
13          Merc 450SLC  15.2          8         275.8         180   
14   Cadillac Fleetwood  10.4          8         472.0         205   
15  Lincoln Continental  10.4          8         460.0         215   
16    Chrysler Imperial  14.7          8         440.0         230   
21     Dodge Challenger  15.5          8         318.0         150   
22          AMC Javelin  15.2          8         304.0         150   
23           Camaro Z28  13.3          8         350.0         245   
24     Pontiac Firebird  19.2          8         400.0         175   
28       Ford Pantera L  15.8          8         351.0         264   
29         Ferrari Dino  19.7          6         145.0         175   
30        Maserati Bora  15.0          8         301.0         335   

    rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
0              3.90   2.620              16.46            0             1   
1              3.90   2.875              17.02            0             1   
3              3.08   3.215              19.44            1             0   
4              3.15   3.440              17.02            0             0   
5              2.76   3.460              20.22            1             0   
6              3.21   3.570              15.84            0             0   
9              3.92   3.440              18.30            1             0   
10             3.92   3.440              18.90            1             0   
11             3.07   4.070              17.40            0             0   
12             3.07   3.730              17.60            0             0   
13             3.07   3.780              18.00            0             0   
14             2.93   5.250              17.98            0             0   
15             3.00   5.424              17.82            0             0   
16             3.23   5.345              17.42            0             0   
21             2.76   3.520              16.87            0             0   
22             3.15   3.435              17.30            0             0   
23             3.73   3.840              15.41            0             0   
24             3.08   3.845              17.05            0             0   
28             4.22   3.170              14.50            0             1   
29             3.62   2.770              15.50            0             1   
30             3.54   3.570              14.60            0             1   

    gears  carburetors  
0       4            4  
1       4            4  
3       3            1  
4       3            2  
5       3            1  
6       3            4  
9       4            4  
10      4            4  
11      3            3  
12      3            3  
13      3            3  
14      3            4  
15      3            4  
16      3            4  
21      3            2  
22      3            2  
23      3            4  
24      3            2  
28      5            4  
29      5            6  
30      5            8

In [27]:
# Extract all rows that contain part of a string
cars[cars["brand"].str.contains("Merc")]

brand   mpg  cylinders  displacement  horsepower  rear_axle_ratio  \
7     Merc 240D  24.4          4         146.7          62             3.69   
8      Merc 230  22.8          4         140.8          95             3.92   
9      Merc 280  19.2          6         167.6         123             3.92   
10    Merc 280C  17.8          6         167.6         123             3.92   
11   Merc 450SE  16.4          8         275.8         180             3.07   
12   Merc 450SL  17.3          8         275.8         180             3.07   
13  Merc 450SLC  15.2          8         275.8         180             3.07   

    weight  quarter_mile_time  engine_type  transmission  gears  carburetors  
7     3.19               20.0            1             0      4            2  
8     3.15               22.9            1             0      4            2  
9     3.44               18.3            1             0      4            4  
10    3.44               18.9            1             0      4            4  
11    4.07               17.4            0             0      3            3  
12    3.73               17.6            0             0      3            3  
13    3.78               18.0            0             0      3            3

In [28]:
# Extract all rows that contain part of a string
cars[cars["gears"].isin([4,5])]

brand   mpg  cylinders  displacement  horsepower  \
0        Mazda RX4  21.0          6         160.0         110   
1    Mazda RX4 Wag  21.0          6         160.0         110   
2       Datsun 710  22.8          4         108.0          93   
7        Merc 240D  24.4          4         146.7          62   
8         Merc 230  22.8          4         140.8          95   
9         Merc 280  19.2          6         167.6         123   
10       Merc 280C  17.8          6         167.6         123   
17        Fiat 128  32.4          4          78.7          66   
18     Honda Civic  30.4          4          75.7          52   
19  Toyota Corolla  33.9          4          71.1          65   
25       Fiat X1-9  27.3          4          79.0          66   
26   Porsche 914-2  26.0          4         120.3          91   
27    Lotus Europa  30.4          4          95.1         113   
28  Ford Pantera L  15.8          8         351.0         264   
29    Ferrari Dino  19.7          6         145.0         175   
30   Maserati Bora  15.0          8         301.0         335   
31      Volvo 142E  21.4          4         121.0         109   

    rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
0              3.90   2.620              16.46            0             1   
1              3.90   2.875              17.02            0             1   
2              3.85   2.320              18.61            1             1   
7              3.69   3.190              20.00            1             0   
8              3.92   3.150              22.90            1             0   
9              3.92   3.440              18.30            1             0   
10             3.92   3.440              18.90            1             0   
17             4.08   2.200              19.47            1             1   
18             4.93   1.615              18.52            1             1   
19             4.22   1.835              19.90            1             1   
25             4.08   1.935              18.90            1             1   
26             4.43   2.140              16.70            0             1   
27             3.77   1.513              16.90            1             1   
28             4.22   3.170              14.50            0             1   
29             3.62   2.770              15.50            0             1   
30             3.54   3.570              14.60            0             1   
31             4.11   2.780              18.60            1             1   

    gears  carburetors  
0       4            4  
1       4            4  
2       4            1  
7       4            2  
8       4            2  
9       4            4  
10      4            4  
17      4            1  
18      4            2  
19      4            1  
25      4            1  
26      5            2  
27      5            2  
28      5            4  
29      5            6  
30      5            8  
31      4            2

In [29]:
cars1 = cars[:5]
cars2 = cars[27:]
# concatenate dataframes, axis determines whether to concatenate rows or columns, 
# ignore_index renames the rows or columns with numbers
pd.concat([cars1, cars2], axis=0, ignore_index=True)

brand   mpg  cylinders  displacement  horsepower  \
0          Mazda RX4  21.0          6         160.0         110   
1      Mazda RX4 Wag  21.0          6         160.0         110   
2         Datsun 710  22.8          4         108.0          93   
3     Hornet 4 Drive  21.4          6         258.0         110   
4  Hornet Sportabout  18.7          8         360.0         175   
5       Lotus Europa  30.4          4          95.1         113   
6     Ford Pantera L  15.8          8         351.0         264   
7       Ferrari Dino  19.7          6         145.0         175   
8      Maserati Bora  15.0          8         301.0         335   
9         Volvo 142E  21.4          4         121.0         109   

   rear_axle_ratio  weight  quarter_mile_time  engine_type  transmission  \
0             3.90   2.620              16.46            0             1   
1             3.90   2.875              17.02            0             1   
2             3.85   2.320              18.61            1             1   
3             3.08   3.215              19.44            1             0   
4             3.15   3.440              17.02            0             0   
5             3.77   1.513              16.90            1             1   
6             4.22   3.170              14.50            0             1   
7             3.62   2.770              15.50            0             1   
8             3.54   3.570              14.60            0             1   
9             4.11   2.780              18.60            1             1   

   gears  carburetors  
0      4            4  
1      4            4  
2      4            1  
3      3            1  
4      3            2  
5      5            2  
6      5            4  
7      5            6  
8      5            8  
9      4            2

### Functions and applying
One on the best feature of pandas is that you don't have to loop through each row to manipulate the values in each cell. Instead, use built in functions or use the `apply()` function to apply your own function!

In [30]:
def tons_to_kg(x):
    return (x * 1000) * 0.4536

In [31]:
# Use the apply function with the function name as the input
# You must reassign the column to overwrite the old one
# You can also specify axis to select whether you want to apply by column or row
cars["weight"] = cars["weight"].apply(tons_to_kg)
cars.head()

brand   mpg  cylinders  displacement  horsepower  \
0          Mazda RX4  21.0          6         160.0         110   
1      Mazda RX4 Wag  21.0          6         160.0         110   
2         Datsun 710  22.8          4         108.0          93   
3     Hornet 4 Drive  21.4          6         258.0         110   
4  Hornet Sportabout  18.7          8         360.0         175   

   rear_axle_ratio    weight  quarter_mile_time  engine_type  transmission  \
0             3.90  1188.432              16.46            0             1   
1             3.90  1304.100              17.02            0             1   
2             3.85  1052.352              18.61            1             1   
3             3.08  1458.324              19.44            1             0   
4             3.15  1560.384              17.02            0             0   

   gears  carburetors  
0      4            4  
1      4            4  
2      4            1  
3      3            1  
4      3            2

### Groupby
The groupby function allows you to easily perform aggregation functions on your dataset for specific subsets of your data.

In [33]:
# Creating a quick function to calculate the average of the quarter_mile_time
def avg_time(x):
    df = x["quarter_mile_time"]
    return sum(df)/len(df)

In [34]:
# Groups the dataframe by the number of carburetors and calculates the average time for the number of carburetors each car has
cars.groupby("carburetors").apply(avg_time)

carburetors
1    19.507143
2    18.186000
3    17.666667
4    16.965000
6    15.500000
8    14.600000
dtype: float64

### Pivoting (Long to Wide)
Pivoting is a useful function for converting a long pandas table to a wide table. A long table is a table where each value has it's own row. A wide output is more like a typical excel table, where different values of different categories are in different columns. Converting a long table to a wide table is useful when you would like to create new columns from existing columns.

In [16]:
long_data = pd.DataFrame(data = {'value': [20, 15, 42,
                                              20, 10, 32,
                                              20, 4, 22,
                                              20, 19, 25,
                                              20, 25, 31,
                                              20, 18, 32,
                                              20, 14, 52,
                                              20, 4, 12,
                                              20, 13, 23,
                                              20, 26, 35],
                                    'scan_multiplier': [1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,
                                                   1, 0.1, 10,],
                                    'feature': ['KD', 'KD', 'KD', 
                                                'receptor/cell', 'receptor/cell', 'receptor/cell', 
                                                '# of cells', '# of cells', '# of cells', 
                                                'avidity', 'avidity', 'avidity', 
                                                'tumor volume', 'tumor volume', 'tumor volume',
                                                'KD', 'KD', 'KD', 
                                                'receptor/cell', 'receptor/cell', 'receptor/cell', 
                                                '# of cells', '# of cells', '# of cells', 
                                                'avidity', 'avidity', 'avidity', 
                                                'tumor volume', 'tumor volume', 'tumor volume'],
                                    'cell_line': ['low', 'low', 'low',
                                                  'low', 'low', 'low',
                                                  'low', 'low', 'low',
                                                  'low', 'low', 'low',
                                                  'low', 'low', 'low',
                                                  'high', 'high', 'high',
                                                 'high', 'high', 'high',
                                                 'high', 'high', 'high',
                                                 'high', 'high', 'high',
                                                 'high', 'high', 'high',
                                                 ]})
long_data

value  scan_multiplier        feature cell_line
0      20              1.0             KD       low
1      15              0.1             KD       low
2      42             10.0             KD       low
3      20              1.0  receptor/cell       low
4      10              0.1  receptor/cell       low
5      32             10.0  receptor/cell       low
6      20              1.0     # of cells       low
7       4              0.1     # of cells       low
8      22             10.0     # of cells       low
9      20              1.0        avidity       low
10     19              0.1        avidity       low
11     25             10.0        avidity       low
12     20              1.0   tumor volume       low
13     25              0.1   tumor volume       low
14     31             10.0   tumor volume       low
15     20              1.0             KD      high
16     18              0.1             KD      high
17     32             10.0             KD      high
18     20              1.0  receptor/cell      high
19     14              0.1  receptor/cell      high
20     52             10.0  receptor/cell      high
21     20              1.0     # of cells      high
22      4              0.1     # of cells      high
23     12             10.0     # of cells      high
24     20              1.0        avidity      high
25     13              0.1        avidity      high
26     23             10.0        avidity      high
27     20              1.0   tumor volume      high
28     26              0.1   tumor volume      high
29     35             10.0   tumor volume      high

To convert a data from long to wide, the pivot function is used. Three arguments must be supplied to the pivot function:
* index: Index are a list of the columns that will be untouched and determine the new rows in the table. There must be only one unique value for each unique combination of variables in the index and columns.
* columns: This is the column that will determine the column names for the split values
* values: This is the column that will be split into multiple columns

In [18]:
# Convert values and scan_multiplier to columns
wide_data = long_data.pivot(index=["cell_line", "feature"], columns="scan_multiplier", values="value")
# Reset index to make index into a column
wide_data = wide_data.reset_index()
wide_data

scan_multiplier cell_line        feature  0.1  1.0  10.0
0                    high     # of cells    4   20    12
1                    high             KD   18   20    32
2                    high        avidity   13   20    23
3                    high  receptor/cell   14   20    52
4                    high   tumor volume   26   20    35
5                     low     # of cells    4   20    22
6                     low             KD   15   20    42
7                     low        avidity   19   20    25
8                     low  receptor/cell   10   20    32
9                     low   tumor volume   25   20    31

### Melt (Wide to long)
Sometimes it is important to convert from wide to long, such as when trying to plot data. The long format is useful since each row contains all the labels that is needed for plotting. There are 2 arguments for melt:
* id_vars: These are the columns you do not want to pivot and not combine.
* value_vars: These are the columns that you want to combine. Two columns will be created, a category column with the name of the columns as the name (can change with `var_name`) and a value columns with the values from all the columns (can change with `value_name`).

In [48]:
wide_data

scan_multiplier cell_line        feature  0.1  1.0  10.0
0                    high     # of cells    4   20    12
1                    high             KD   18   20    32
2                    high        avidity   13   20    23
3                    high  receptor/cell   14   20    52
4                    high   tumor volume   26   20    35
5                     low     # of cells    4   20    22
6                     low             KD   15   20    42
7                     low        avidity   19   20    25
8                     low  receptor/cell   10   20    32
9                     low   tumor volume   25   20    31

In [50]:
long_data_2 = pd.melt(wide_data, id_vars=['feature', 'cell_line'], value_vars=[0.1, 1.0, 10.0],
                      var_name = 'scan_multiplier', value_name = 'measurements')
long_data_2

feature cell_line scan_multiplier  measurements
0      # of cells      high             0.1             4
1              KD      high             0.1            18
2         avidity      high             0.1            13
3   receptor/cell      high             0.1            14
4    tumor volume      high             0.1            26
5      # of cells       low             0.1             4
6              KD       low             0.1            15
7         avidity       low             0.1            19
8   receptor/cell       low             0.1            10
9    tumor volume       low             0.1            25
10     # of cells      high             1.0            20
11             KD      high             1.0            20
12        avidity      high             1.0            20
13  receptor/cell      high             1.0            20
14   tumor volume      high             1.0            20
15     # of cells       low             1.0            20
16             KD       low             1.0            20
17        avidity       low             1.0            20
18  receptor/cell       low             1.0            20
19   tumor volume       low             1.0            20
20     # of cells      high            10.0            12
21             KD      high            10.0            32
22        avidity      high            10.0            23
23  receptor/cell      high            10.0            52
24   tumor volume      high            10.0            35
25     # of cells       low            10.0            22
26             KD       low            10.0            42
27        avidity       low            10.0            25
28  receptor/cell       low            10.0            32
29   tumor volume       low            10.0            31